version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "primer-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wr2z3sgd3orn"
s3_prefix = "primer-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

